name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [x86_64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - Name: Setup Go
        uses: actions/setup-go@v5

      - name: Build
        run: go build

      - name: Tests
        run: |
          cd tests
          ./rere.py replay test.list
